'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Check, Filter, Heart, RotateCcw, Search, Trophy, X } from 'lucide-react';
import { HISTORY_EVENTS, Locale } from '@/data/history';

type QuizQuestion = { question: { vi: string; en: string }; options: { vi: string; en: string }[]; answer: number };
const QUIZ: QuizQuestion[] = [
  { question: { vi: 'Bộ luật Hammurabi gắn với nền văn minh nào?', en: 'Which civilization is associated with the Code of Hammurabi?' }, options: [{ vi: 'Babylon', en: 'Babylon' }, { vi: 'Maya', en: 'Maya' }, { vi: 'Inca', en: 'Inca' }], answer: 0 },
  { question: { vi: 'Con đường Tơ lụa kết nối chủ yếu những khu vực nào?', en: 'Which regions did the Silk Roads primarily connect?' }, options: [{ vi: 'Đông Á và Địa Trung Hải', en: 'East Asia and the Mediterranean' }, { vi: 'Nam Cực và Bắc Cực', en: 'Antarctica and the Arctic' }, { vi: 'Úc và Hawaii', en: 'Australia and Hawaii' }], answer: 0 },
  { question: { vi: 'Apollo 11 đưa con người đến đâu?', en: 'Where did Apollo 11 take humans?' }, options: [{ vi: 'Sao Hỏa', en: 'Mars' }, { vi: 'Mặt Trăng', en: 'The Moon' }, { vi: 'Sao Kim', en: 'Venus' }], answer: 1 },
  { question: { vi: 'Cách mạng công nghiệp bắt đầu mạnh mẽ ở đâu?', en: 'Where did the Industrial Revolution begin?' }, options: [{ vi: 'Anh', en: 'Britain' }, { vi: 'Brazil', en: 'Brazil' }, { vi: 'Ai Cập', en: 'Egypt' }], answer: 0 },
  { question: { vi: 'Tuyên ngôn Nhân quyền Toàn cầu được thông qua sau sự kiện nào?', en: 'The Universal Declaration of Human Rights was adopted after which event?' }, options: [{ vi: 'Thế chiến thứ hai', en: 'World War II' }, { vi: 'Cách mạng Pháp', en: 'French Revolution' }, { vi: 'Thời đại đồ đồng', en: 'Bronze Age' }], answer: 0 },
];

export default function AtlasFeatures({ locale }: { locale: Locale }) {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('all');
  const [page, setPage] = useState(1);
  const [favorites, setFavorites] = useState<number[]>(() => { if (typeof window === 'undefined') return []; const saved = window.localStorage.getItem('atlas-favorites'); return saved ? JSON.parse(saved) : []; });
  const [quizIndex, setQuizIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [answered, setAnswered] = useState<number | null>(null);
  const [customQuestions, setCustomQuestions] = useState<QuizQuestion[]>(() => { if (typeof window === 'undefined') return []; const saved = window.localStorage.getItem('atlas-custom-quiz'); return saved ? JSON.parse(saved) : []; });
  const [newQuestion, setNewQuestion] = useState({ question: '', optionA: '', optionB: '', optionC: '', answer: 0 });
  const text = (vi: string, en: string) => locale === 'vi' ? vi : en;
  const questions = [...QUIZ, ...customQuestions];
  const categories = useMemo(() => Array.from(new Set(HISTORY_EVENTS.map(event => event.category[locale]))), [locale]);
  const filtered = useMemo(() => HISTORY_EVENTS.filter(event => { const haystack = `${event.title[locale]} ${event.summary[locale]} ${event.region[locale]}`.toLowerCase(); return haystack.includes(search.toLowerCase()) && (category === 'all' || event.category[locale] === category); }), [category, locale, search]);
  const pageSize = 8;
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const visibleEvents = filtered.slice((page - 1) * pageSize, page * pageSize);
  const toggleFavorite = (id: number) => { const next = favorites.includes(id) ? favorites.filter(item => item !== id) : [...favorites, id]; setFavorites(next); window.localStorage.setItem('atlas-favorites', JSON.stringify(next)); };
  const answerQuiz = (answer: number) => { if (answered !== null) return; setAnswered(answer); if (answer === questions[quizIndex].answer) setScore(value => value + 1); };
  const nextQuestion = () => { setAnswered(null); setQuizIndex(value => (value + 1) % questions.length); };
  const addQuestion = (event: React.FormEvent) => { event.preventDefault(); if (!newQuestion.question.trim() || !newQuestion.optionA.trim() || !newQuestion.optionB.trim() || !newQuestion.optionC.trim()) return; const question: QuizQuestion = { question: { vi: newQuestion.question, en: newQuestion.question }, options: [{ vi: newQuestion.optionA, en: newQuestion.optionA }, { vi: newQuestion.optionB, en: newQuestion.optionB }, { vi: newQuestion.optionC, en: newQuestion.optionC }], answer: newQuestion.answer }; const next = [...customQuestions, question]; setCustomQuestions(next); window.localStorage.setItem('atlas-custom-quiz', JSON.stringify(next)); setNewQuestion({ question: '', optionA: '', optionB: '', optionC: '', answer: 0 }); };

  return <>
    <section className="atlas-tools-section container-port" id="explore"><div className="atlas-section-heading"><div><p className="atlas-eyebrow">03 / {text('THƯ VIỆN', 'LIBRARY')}</p><h2>{text('Tìm đúng câu chuyện.', 'Find your story.')}</h2></div><span className="atlas-library-count">{filtered.length} / {HISTORY_EVENTS.length}</span></div><div className="atlas-filter-bar"><label className="atlas-filter-search"><Search size={16} /><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder={text('Tìm sự kiện, vùng đất...', 'Search events, regions...')} /></label><label className="atlas-filter-select"><Filter size={15} /><select value={category} onChange={event => { setCategory(event.target.value); setPage(1); }}><option value="all">{text('Tất cả chủ đề', 'All topics')}</option>{categories.map(item => <option value={item} key={item}>{item}</option>)}</select></label></div><div className="atlas-results-grid">{visibleEvents.map(event => <article className="atlas-result" key={event.id}><div className="atlas-event-meta"><span>{event.year}</span><button type="button" aria-label={text('Lưu yêu thích', 'Save favorite')} onClick={() => toggleFavorite(event.id)} className={favorites.includes(event.id) ? 'favorite active' : 'favorite'}><Heart size={15} fill={favorites.includes(event.id) ? 'currentColor' : 'none'} /></button></div><Link href={`/events/${event.id}`}><h3>{event.title[locale]}</h3><p>{event.summary[locale]}</p></Link><footer><span>{event.region[locale]}</span>{favorites.includes(event.id) && <span className="saved-label">{text('ĐÃ LƯU', 'SAVED')}</span>}</footer></article>)}</div>{filtered.length === 0 && <div className="atlas-empty">{text('Không tìm thấy sự kiện phù hợp.', 'No matching events found.')}</div>}{filtered.length > 0 && <nav className="atlas-pagination" aria-label={text('Phân trang sự kiện', 'Event pagination')}><button type="button" disabled={page === 1} onClick={() => setPage(value => value - 1)}>←</button><span>{page} / {pageCount}</span><button type="button" disabled={page === pageCount} onClick={() => setPage(value => value + 1)}>→</button></nav>}</section>
    <section className="atlas-quiz container-port" id="quiz"><div className="quiz-intro"><p className="atlas-eyebrow">04 / QUIZ</p><h2>{text('Bạn nhớ được bao nhiêu?', 'How much do you remember?')}</h2><p>{text('Một bài kiểm tra nhanh để biến tò mò thành kiến thức.', 'A quick challenge to turn curiosity into knowledge.')}</p><form className="quiz-create" onSubmit={addQuestion}><strong>{text('Tạo câu hỏi mới', 'Create a question')}</strong><input value={newQuestion.question} onChange={event => setNewQuestion({ ...newQuestion, question: event.target.value })} placeholder={text('Câu hỏi của bạn...', 'Your question...')} /><input value={newQuestion.optionA} onChange={event => setNewQuestion({ ...newQuestion, optionA: event.target.value })} placeholder={text('Đáp án A', 'Answer A')} /><input value={newQuestion.optionB} onChange={event => setNewQuestion({ ...newQuestion, optionB: event.target.value })} placeholder={text('Đáp án B', 'Answer B')} /><input value={newQuestion.optionC} onChange={event => setNewQuestion({ ...newQuestion, optionC: event.target.value })} placeholder={text('Đáp án C', 'Answer C')} /><select value={newQuestion.answer} onChange={event => setNewQuestion({ ...newQuestion, answer: Number(event.target.value) })}><option value={0}>{text('Đáp án đúng: A', 'Correct answer: A')}</option><option value={1}>{text('Đáp án đúng: B', 'Correct answer: B')}</option><option value={2}>{text('Đáp án đúng: C', 'Correct answer: C')}</option></select><button type="submit">{text('Thêm vào quiz', 'Add to quiz')} <Check size={14} /></button></form></div><div className="quiz-card"><div className="quiz-card-top"><span>{String(quizIndex + 1).padStart(2, '0')} / {questions.length}</span><span><Trophy size={14} /> {score} {text('điểm', 'points')}</span></div><h3>{questions[quizIndex].question[locale]}</h3><div className="quiz-options">{questions[quizIndex].options.map((option, index) => <button type="button" key={option.vi} className={answered === null ? '' : index === questions[quizIndex].answer ? 'correct' : index === answered ? 'wrong' : ''} onClick={() => answerQuiz(index)}>{answered !== null && index === questions[quizIndex].answer && <Check size={15} />}{answered !== null && index === answered && index !== questions[quizIndex].answer && <X size={15} />}{option[locale]}</button>)}</div>{answered !== null && <button type="button" className="quiz-next" onClick={nextQuestion}>{text('Câu tiếp theo', 'Next question')} <RotateCcw size={14} /></button>}</div></section>
  </>;
}
